"""Added created_at field for the Message model

Revision ID: 735126895a41
Revises: 13c1ff4e5f42
Create Date: 2024-05-01 14:40:58.685908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735126895a41'
down_revision = '13c1ff4e5f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
